from userprofile.views.token import MyTokenObtainPairView
from userprofile.views.forgot_password import ForgotPasswordView, ResetPasswordView
from userprofile.views.file import FileUploadGenericView, FileListGenericView
